#include "array.c"
#include "assets.c"
#include "boolean.h"
//#include "command.c"
#include "graph.c"
#include "listlinier.c"
#include "load.c"
#include "matriks.c"
// #include "pcolor.c"
#include "player.c"
#include "point.c"
#include "queue.c"
#include "save.c"
#include "stackt.c"
#include "mesinkata_faris.c"
#include "mesinkar_faris.c"
